version: 1.0.0.{build}
build_script:
- cmd: >-
    REM Core

    dotnet restore



    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.BootConfig

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Complete

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Containers

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Dmg

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Ext

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Fat

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.FileSystems

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.HfsPlus

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Iscsi

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Iso9660

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Net

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Nfs

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Ntfs

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.OpticalDiscSharing

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.OpticalDisk

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Registry

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Sdi

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.SquashFs

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Transports

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Udf

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Vdi

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Vhd

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Vhdx

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Vmdk

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Wim

    dotnet pack -c Release -o Nuget\ Library\LordMike.DiscUtils.Xva



    REM Utilities

    dotnet build -c Release Utilities\BCDDump

    dotnet build -c Release Utilities\DiscUtils.Common

    dotnet build -c Release Utilities\DiscUtils.Diagnostics

    dotnet build -c Release Utilities\DiscUtils.PowerShell

    dotnet build -c Release Utilities\DiskClone

    dotnet build -c Release Utilities\DiskDump

    dotnet build -c Release Utilities\DmgExtract

    dotnet build -c Release Utilities\ExternalFileSystem

    dotnet build -c Release Utilities\FileExtract

    dotnet build -c Release Utilities\FileRecover

    dotnet build -c Release Utilities\iSCSIBrowse

    dotnet build -c Release Utilities\ISOCreate

    dotnet build -c Release Utilities\MSBuildTask

    dotnet build -c Release Utilities\NTFSDump

    dotnet build -c Release Utilities\ODSBrowse

    dotnet build -c Release Utilities\OSClone

    dotnet build -c Release Utilities\VHDCreate

    dotnet build -c Release Utilities\VHDDump

    dotnet build -c Release Utilities\VHDXDump

    dotnet build -c Release Utilities\VirtualDiskConvert

    dotnet build -c Release Utilities\VolInfo


    REM Tests

    dotnet build -c Release Tests\LibraryTests
test_script:
- cmd: dotnet test -c Release Tests\LibraryTests
artifacts:
- path: Nuget\*.nupkg