image: Visual Studio 2019
install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: >-
      $version = ConvertFrom-Json $($(GitVersion) -join "")
      
      $content = Get-Content .\Version.template.props -Raw;
      $content = $content.Replace("&InformationalVersion&", $version.InformationalVersion);
      $content = $content.Replace("&FileVersion&", $version.AssemblySemFileVer);
      $content = $content.Replace("&AssemblyVersion&", $version.AssemblySemVer);
      $content = $content.Replace("&NugetVersion&", $version.NuGetVersion);
      Set-Content .\Version.props $content;
      
      Update-AppveyorBuild -Version $version.NuGetVersion
  - msbuild /t:Restore /Verbosity:Minimal

build_script:
  - cmd: msbuild /t:build /p:Configuration=Release /Verbosity:Minimal

after_build:
  - cmd: msbuild /t:pack /p:Configuration=Release /p:IncludeSymbols=true /Verbosity:Minimal /p:NoBuild=true

test_script:
  - cmd: cd Tests\LibraryTests\bin\Release\netcoreapp2.0
  - cmd: dotnet test ..\..\..\LibraryTests.csproj -c Release --no-build --logger:trx -- RunConfiguration.TargetPlatform="x64" RunConfiguration.DisableParallelization="true"

artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.snupkg'

deploy:
  - provider: NuGet
    server: https://api.nuget.org/v3/index.json
    symbol_server: https://api.nuget.org/v3/index.json
    artifact: /.*\.s?nupkg/
    api_key:
      secure: 1zdVvAQJbpFDsKJS/TXQLc6GI6SlZueTSCcL7xbK6QMisvL8V5nhLFgrceLfp1Ak
    on:
      branch: nuget