version: 1.0.0.{build}
build_script:
- cmd: >-
    REM Core

    dotnet restore Library\DiscUtils

    dotnet restore Library\DiscUtils.BootConfig

    dotnet restore Library\DiscUtils.Complete

    dotnet restore Library\DiscUtils.Containers

    dotnet restore Library\DiscUtils.Dmg

    dotnet restore Library\DiscUtils.Ext

    dotnet restore Library\DiscUtils.Fat

    dotnet restore Library\DiscUtils.FileSystems

    dotnet restore Library\DiscUtils.HfsPlus

    dotnet restore Library\DiscUtils.Iscsi

    dotnet restore Library\DiscUtils.Iso9660

    dotnet restore Library\DiscUtils.Net

    dotnet restore Library\DiscUtils.Nfs

    dotnet restore Library\DiscUtils.Ntfs

    dotnet restore Library\DiscUtils.OpticalDiscSharing

    dotnet restore Library\DiscUtils.OpticalDisk

    dotnet restore Library\DiscUtils.Registry

    dotnet restore Library\DiscUtils.Sdi

    dotnet restore Library\DiscUtils.SquashFs

    dotnet restore Library\DiscUtils.Transports

    dotnet restore Library\DiscUtils.Udf

    dotnet restore Library\DiscUtils.Vdi

    dotnet restore Library\DiscUtils.Vhd

    dotnet restore Library\DiscUtils.Vhdx

    dotnet restore Library\DiscUtils.Vmdk

    dotnet restore Library\DiscUtils.Wim

    dotnet restore Library\DiscUtils.Xva


    dotnet build -c Release Library\DiscUtils

    dotnet build -c Release Library\DiscUtils.BootConfig

    dotnet build -c Release Library\DiscUtils.Complete

    dotnet build -c Release Library\DiscUtils.Containers

    dotnet build -c Release Library\DiscUtils.Dmg

    dotnet build -c Release Library\DiscUtils.Ext

    dotnet build -c Release Library\DiscUtils.Fat

    dotnet build -c Release Library\DiscUtils.FileSystems

    dotnet build -c Release Library\DiscUtils.HfsPlus

    dotnet build -c Release Library\DiscUtils.Iscsi

    dotnet build -c Release Library\DiscUtils.Iso9660

    dotnet build -c Release Library\DiscUtils.Net

    dotnet build -c Release Library\DiscUtils.Nfs

    dotnet build -c Release Library\DiscUtils.Ntfs

    dotnet build -c Release Library\DiscUtils.OpticalDiscSharing

    dotnet build -c Release Library\DiscUtils.OpticalDisk

    dotnet build -c Release Library\DiscUtils.Registry

    dotnet build -c Release Library\DiscUtils.Sdi

    dotnet build -c Release Library\DiscUtils.SquashFs

    dotnet build -c Release Library\DiscUtils.Transports

    dotnet build -c Release Library\DiscUtils.Udf

    dotnet build -c Release Library\DiscUtils.Vdi

    dotnet build -c Release Library\DiscUtils.Vhd

    dotnet build -c Release Library\DiscUtils.Vhdx

    dotnet build -c Release Library\DiscUtils.Vmdk

    dotnet build -c Release Library\DiscUtils.Wim

    dotnet build -c Release Library\DiscUtils.Xva


    REM Utilities

    dotnet restore Utilities\BCDDump

    dotnet restore Utilities\DiscUtils.Common

    dotnet restore Utilities\DiscUtils.Diagnostics

    dotnet restore Utilities\DiscUtils.PowerShell

    dotnet restore Utilities\DiskClone

    dotnet restore Utilities\DiskDump

    dotnet restore Utilities\DmgExtract

    dotnet restore Utilities\ExternalFileSystem

    dotnet restore Utilities\FileExtract

    dotnet restore Utilities\FileRecover

    dotnet restore Utilities\iSCSIBrowse

    dotnet restore Utilities\ISOCreate

    dotnet restore Utilities\MSBuildTask

    dotnet restore Utilities\NTFSDump

    dotnet restore Utilities\ODSBrowse

    dotnet restore Utilities\OSClone

    dotnet restore Utilities\VHDCreate

    dotnet restore Utilities\VHDDump

    dotnet restore Utilities\VHDXDump

    dotnet restore Utilities\VirtualDiskConvert

    dotnet restore Utilities\VolInfo


    dotnet build -c Release Utilities\BCDDump

    dotnet build -c Release Utilities\DiscUtils.Common

    dotnet build -c Release Utilities\DiscUtils.Diagnostics

    dotnet build -c Release Utilities\DiscUtils.PowerShell

    dotnet build -c Release Utilities\DiskClone

    dotnet build -c Release Utilities\DiskDump

    dotnet build -c Release Utilities\DmgExtract

    dotnet build -c Release Utilities\ExternalFileSystem

    dotnet build -c Release Utilities\FileExtract

    dotnet build -c Release Utilities\FileRecover

    dotnet build -c Release Utilities\iSCSIBrowse

    dotnet build -c Release Utilities\ISOCreate

    dotnet build -c Release Utilities\MSBuildTask

    dotnet build -c Release Utilities\NTFSDump

    dotnet build -c Release Utilities\ODSBrowse

    dotnet build -c Release Utilities\OSClone

    dotnet build -c Release Utilities\VHDCreate

    dotnet build -c Release Utilities\VHDDump

    dotnet build -c Release Utilities\VHDXDump

    dotnet build -c Release Utilities\VirtualDiskConvert

    dotnet build -c Release Utilities\VolInfo


    REM Tests

    dotnet restore Tests\LibraryTests

    dotnet build -c Release Tests\LibraryTests
test_script:
- cmd: dotnet test -c Release Tests\LibraryTests
deploy_script:
- cmd: >-
    dotnet pack -c Release -o Nuget\ Library\DiscUtils

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.BootConfig

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Complete

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Containers

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Dmg

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Ext

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Fat

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.FileSystems

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.HfsPlus

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Iscsi

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Iso9660

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Net

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Nfs

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Ntfs

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.OpticalDiscSharing

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.OpticalDisk

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Registry

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Sdi

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.SquashFs

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Transports

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Udf

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Vdi

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Vhd

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Vhdx

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Vmdk

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Wim

    dotnet pack -c Release -o Nuget\ Library\DiscUtils.Xva